name: Build docs

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Tag Name example
        run: |
          echo "Status: *release* $GITHUB_REF_NAME" > release.md
          
      - name: setup-micromamba
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Install tinytex
        shell: micromamba-shell {0}
        run: quarto install tinytex
      - name: Build docs
        shell: micromamba-shell {0}
        run: quarto render .

      - name: Push docs to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
